version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: file_management
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork

volumes:
  mongo_data:

networks:
  mynetwork:
    driver: bridge